chatbot: Changes to Rule of Five
Change copy constructor and copy assignment constructor, such that
they init. pointers and copy objetcs.
Exception: Shallow copy for ChatLogic, because _nodes in ChatLogic class
is a vector of unique_ptr.